## Minimal SMB Server image based on Alpine adjusted for use in k8s Windows
FROM andyzhangx/samba:win-fix

ARG src="./IPG/carmaker"
ARG trg="/smbshare/"
COPY ${src} ${trg}


# TODO: Need to adjust SMB permissions so that all shared contents are executable.
RUN chown -R root /smbshare/ && \
    chgrp -R root /smbshare/ && \
    chmod -R +rwx /smbshare/