apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-project-linux
  labels:
    app: carmaker
    carmaker-version: "12"
    matlab-version: "2022b"
    os: "linux"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carmaker
      carmaker-version: "12"
      matlab-version: "2022b"
      os: "linux"
  template:
    metadata:
      labels:
        app: carmaker
        carmaker-version: "12"
        matlab-version: "2022b"
        os: "linux"
    spec:
      containers:
      - name: cm-project-linux
        image: yeonsoopark/cm-run:v1.3
        volumeMounts:
          - name: nfs-linux-cm-12
            mountPath: /opt/ipg/carmaker/linux64-12.0.1
          - name: nfs-linux-matlab-2022b
            mountPath: /usr/local/MATLAB/R2022b
      volumes:
      - name: nfs-linux-cm-12
        persistentVolumeClaim:
          claimName: nfs-linux-cm-12
      - name: nfs-linux-matlab-2022b
        persistentVolumeClaim:
          claimName: nfs-linux-matlab-2022b
