apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-linux-cm-13
  labels:
    carmaker-version: "13"
    os: "linux"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.0.162
    path: "/opt/ipg/carmaker/linux64-13.0.1"
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-linux-cm-12
  labels:
    carmaker-version: "12"
    os: "linux"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.0.162
    path: "/opt/ipg/carmaker/linux64-12.0.1"
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-linux-cm-11
  labels:
    carmaker-version: "11"
    os: "linux"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.0.162
    path: "/opt/ipg/carmaker/linux64-11.1.2"
