---
kind: Service
apiVersion: v1
metadata:
  name: matlab-windows-smb
  labels:
    app: matlab-windows-smb
spec:
  type: LoadBalancer
  selector:
    app: matlab-windows-smb
  ports:
    - port: 445
      name: matlab-windows-smb
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: matlab-windows-smb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matlab-windows-smb
  template:
    metadata:
      name: matlab-windows-smb
      labels:
        app: matlab-windows-smb
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: matlab-windows-smb
          image: yeonsoopark/matlab-windows-smb:R2022b
          imagePullPolicy: Always
          env:
            - name: PERMISSIONS
              value: "0777"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: smbcreds2
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smbcreds2
                  key: password
          args: ["-u", "$(USERNAME);$(PASSWORD)", "-s", "share;/smbshare/;yes;no;yes;all;none", "-p"]

