kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cm-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cm-windows-smb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-matlab-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: matlab-windows-smb
