---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cm-windows-smb
provisioner: smb.csi.k8s.io
parameters:
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  source: "//cm-windows-smb.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds2"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: matlab-windows-smb
provisioner: smb.csi.k8s.io
parameters:
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  source: "//matlab-windows-smb.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds2"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
