apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-windows-matlab-2022b
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      matlab-version: "2022b"
      os: "windows"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-windows-matlab-2020b
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      matlab-version: "2020b"
      os: "windows"
