apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-project-windows
  labels:
    app: carmaker
    carmaker-version: "12"
    matlab-version: "2022b"
    os: "windows"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carmaker
      carmaker-version: "12"
      matlab-version: "2022b"
      os: "windows"
  template:
    metadata:
      labels:
        app: carmaker
        carmaker-version: "12"
        matlab-version: "2022b"
        os: "windows"
    spec:
      containers:
      - name: cm-project-windows
        image: mcr.microsoft.com/windows:ltsc2019 #yeonsoopark/cm-windows:v1.0-ltsc2019
#        volumeMounts:
#          - name: nfs-windows-cm-12
#            mountPath: "C:/ipg/carmaker/linux64-12.0.1"
#          - name: nfs-windows-matlab-2022b
#            mountPath: "C:/Program Files/MATLAB/R2022b"
#      volumes:
#      - name: nfs-windows-cm-12
#        persistentVolumeClaim:
#          claimName: nfs-windows-cm-12
#      - name: nfs-windows-matlab-2022b
#        persistentVolumeClaim:
#          claimName: nfs-windows-matlab-2022b
