apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-project-windows
  labels:
    app: carmaker
    carmaker-version: "12"
    matlab-version: "2022b"
    os: "windows"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carmaker
      carmaker-version: "12"
      matlab-version: "2022b"
      os: "windows"
  template:
    metadata:
      labels:
        app: carmaker
        carmaker-version: "12"
        matlab-version: "2022b"
        os: "windows"
    spec:
      containers:
      - name: cm-project-windows
        image: yeonsoopark/cm-windows:v1.0-ltsc2019
        volumeMounts:
            - name: smb
              mountPath: "/ipg/carmaker"
            - name: smb2
              mountPath: "/MATLAB"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
        - name: smb2
          persistentVolumeClaim:
            claimName: pvc-smb2
